### ISSUE TITLE
[CLI] Fix support for non-global installations of galen

### ISSUE THREAD

**Issue by smuldr** [hypery2k/galenframework-cli#23]
Since the 2.1.3 release it has become impossible to install `galenframework-cli` without globally installing the core `galenframework`. 

The output when running `npm install --production` (NodeJS v5.3.0, npm 3.5.3):

```
$ npm install --production 

> galenframework-cli@2.2.1 install /Users/smuldr/Projects/misc/galenframework-cli/cli
> node install.js

Galen installation failed [Error: not found: galen] Error: not found: galen
    at F (/Users/smuldr/Projects/misc/galenframework-cli/cli/node_modules/which/which.js:78:19)
    at E (/Users/smuldr/Projects/misc/galenframework-cli/cli/node_modules/which/which.js:82:29)
    at /Users/smuldr/Projects/misc/galenframework-cli/cli/node_modules/which/which.js:93:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

It seems the install script for the CLI checks where galen is installed, but explicitly excludes the `node_modules/` folder. Is there some workaround for this issue? It would rather not have global node dependencies in our CI machines.

**Comment by hypery2k** [comment]
thanks for reporting this issue, it should require to install the core globally. I'll try to fix this

**Comment by smuldr** [comment]
Thanks for the very speedy response! Could you explain why it should require a global install of the core? 

I would prefer to have a local install, with fallback to global install. The fewer global dependencies the better as far as I'm concerned. Makes CI configuration a lot easier: no need to manually update the CI server whenever we want to update galen.

**Comment by hypery2k** [comment]
it shouldn't require a global install ;)

It's a bug, not a feature ;)

**Comment by hypery2k** [comment]
just as a note: the CLI package is supposed to use for local dev. the core module is supposed for CI environments

**Comment by smuldr** [comment]
Ah, makes sense. I am pretty new with this framework, so forgive me if there are any rookie mistakes. We use gulp to build our app on CI, and the gulp-galen plugin for kicking off galen. Hence the dependency on the CLI.

**Comment by hypery2k** [comment]
you can use my [gulp plugin](https://www.npmjs.com/package/gulp-galenframework) which is a fork of the gulp plugin which doesn't need the CLI package ;)
