### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by pixelass** [hypery2k/galenframework-cli#24]
See: https://github.com/galenframework/galen/issues/375

Cannot install via `npm` or manually.

I was suggested to install Java 7 by @hypery2k  (thx a lot). 
I also found a similar answer here: http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error

This is actually what I did in the beginning but OS X obviously has it's own way of telling you how broken it is. 

OS X would always bring up a prompt directing me to a Java version which would not resolve the prompt. 
After googling I installed https://support.apple.com/kb/DL1572?locale=en_US to make OS X happy and then added Java 7 on top.

F**k you Apple.

I am still making this an issue since this is not mentioned anywhere or the links are not provided. Considering the amount of developers running OS X this might be useful info.

Thx @hypery2k for the help

**Comment by hypery2k** [comment]
you can install Java7 from here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by hypery2k** [comment]
did this helped?

**Comment by msiles** [comment]
Do I need to install java 7 to run Galen?

Moisess-MacBook-Pro:galen-bin-2.2.1 moisessiles$ sudo ./install.sh
ln: /usr/bin/galen: Operation not permitted

**Comment by hypery2k** [comment]
yes you need Java7. and no need to install manually, just install the NPM package globally

**Comment by msiles** [comment]
@hypery2k  I was able to install Galen using this fix

https://github.com/galenframework/galen/blob/master/fordist/install.sh

Thanks
