### ISSUE TITLE
Failing: sudo npm install -g galenframework-cli

### ISSUE THREAD

**Issue by anonym-developer** [hypery2k/galenframework-cli#38]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! galenframework-cli@2.3.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the galenframework-cli@2.3.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs galenframework-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.
```

[npm-debug.txt](https://github.com/hypery2k/galenframework-cli/files/417808/npm-debug.txt)

**Comment by hypery2k** [comment]
you can try the latest master, cd to the cli module and run install -g again. Please post the new output here

**Comment by anonym-developer** [comment]
[npm-debug.txt](https://github.com/hypery2k/galenframework-cli/files/417949/npm-debug.txt)
here you are

**Comment by hypery2k** [comment]
Could you try with Java 7 or 8?

**Comment by anonym-developer** [comment]
my sys preference is telling me I got 8. if i type in `java -version` in terminal, it is 1.6....

![javaversion](https://cloud.githubusercontent.com/assets/5097618/17670003/43ec26d0-6310-11e6-86b5-1bd4cb6d5588.png)

**Comment by anonym-developer** [comment]
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```
[npm-debug.txt](https://github.com/hypery2k/galenframework-cli/files/418403/npm-debug.txt)

**Comment by hypery2k** [comment]
so when running in the terminal java -version you're getting java 6?

**Comment by anonym-developer** [comment]
apparently it is a known [issue](http://stackoverflow.com/questions/12757558/installed-java-7-on-mac-os-x-but-terminal-is-still-using-version-6). I have fixed it by installing the JDK. so my last comment was the result of running the install script from the cli module (as you asked before) – unfortunately the newer java version does not fix the problem.

**Comment by anonym-developer** [comment]
apparently it is a known [issue](http://stackoverflow.com/questions/12757558/installed-java-7-on-mac-os-x-but-terminal-is-still-using-version-6). I have fixed it by installing the JDK. so my last comment was the result of running the install script from the cli module (as you asked before) – unfortunately the newer java version does not fix the problem.

**Comment by hypery2k** [comment]
are you using nvm or just directly installed node?

**Comment by anonym-developer** [comment]
I have just solved the problem for myself. It seams to be a bug with the node version v6.3.1. I updated node to v6.4.0 and now can run the install script.
