### ISSUE TITLE
Shell Init error trying to install Webpack on OSX Sierra

### ISSUE THREAD

**Issue by jedidrew42** [hypery2k/galenframework-cli#41]
Hey all, I am trying to install Webpack on OSX Sierra. I used the Sudo command and this is what I am getting

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3
/usr/local/lib

**Comment by hypery2k** [comment]
did get what's the issue with this project if you're receiving access errors. please post your code...

**Comment by hypery2k** [comment]
closed due to no response
