### ISSUE TITLE
Cant connect to localhost:3000 on OSX Sierra

### ISSUE THREAD

**Issue by jedidrew42** [hypery2k/galenframework-cli#42]
Hello all,

I am trying to use localhost port 3000 as my development environment but I am getting the cant connect message in my browser. Do I need to change my host file or add something to it to get this to work.

**Comment by hypery2k** [comment]
depends what's your concrete setup. Can you post your code? It's possible to use directly from node, see [here](http://galenframework.com/docs/reference-working-in-command-line/#UsageinNodeProjects)

**Comment by hypery2k** [comment]
closed due to no response
