### ISSUE TITLE
Cannot specify custom webdriver path

### ISSUE THREAD

**Issue by yurist38** [hypery2k/galenframework-cli#46]
Hey! I'm trying to run my test with specific webdriver (like there  [http://galenframework.com/docs/browsers/](http://galenframework.com/docs/browsers/)) but it doesn't work. Global version of `galen` seems to use still his "own" driver but the local version doesn't run at all.

So, my command is:
```
./node_modules/galenframework-cli/bin/galen test tests/**/*.test.js -Dwebdriver.chrome.driver=/Users/ydrabik/apps/chromedriver
```

And I'm getting this error:
```
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: The driver executable does not exist: /Users/ydrabik/projects/galen/node_modules/galenframework-cli/node_modules/chromedriver/lib/chromedriver/chromedriver
```

As you see paths are different, seems like passed argument doesn't affect the process. Or I do something wrong? Thanks in advance!

**Comment by hypery2k** [comment]
Could you try with `galenframework-cli@2.3.4-develop-35` and if you want to have verbose logging add NODE_DEBUG=galen:

```
NODE_DEBUG=galen node --debug-brk node_modules/galenframework-cli/bin/galen
```

Can you post the output?

**Comment by yurist38** [comment]
Great! It works with `2.3.4-develop-35` version. So I'm gonna stick with it for now. Thank you!

**Comment by hypery2k** [comment]
ok, cool
