### ISSUE TITLE
Failed: Can't install development version.

### ISSUE THREAD

**Issue by sarbazx** [hypery2k/galenframework-cli#51]
## What did you do?
Failed to install development build.
`npm install -g galenframework-cli@next`

## What did you expect to happen?

wanted to install dev buil of galen.

## What happened instead?
 Failed to install  

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../usr/local/lib/node_modules/core" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taskin/.npm/_logs/2018-02-16T08_54_46_387Z-debug.log
```

## Your Environment

**Galen version:** 2.4
**Java version:** 1.8.0_162
**NodeJS and NPM version:** v9.5.0 and 5.6.0
**Platform(s) running Galen:** macOS High Sierra 10.13.3

**Comment by hypery2k** [comment]
don't get me wrong on this. The @next version is mainly for preview of the npm module and not for Galen. So please don't post issue for a still in development version.
BTW: Galen 2.4 isn't released ;)

**Comment by sarbazx** [comment]
@hypery2k ok, understood.
