### ISSUE TITLE
Docker image not finding galen in $PATH

### ISSUE THREAD

**Issue by rafaelaazevedo** [hypery2k/galenframework-cli#60]
## What did you do?

Run the docker command: `docker run -v galen:/var/test_scripts galenframework/cli galen test /var/test_scripts`

## What did you expect to happen?

My tests should run in the docker container

## What happened instead?

Got the error: `docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"galen\": executable file not found in $PATH": unknown.`

## Your Environment

**Galen version: 2.3.5**
**Java version: java-8-openjdk-amd64**
**NodeJS and NPM version: 6.11.4**
**Platform(s) running Galen: Docker image from  ubuntu:16.04**

## Demo Project

It is not needed atm but here is the the project that I am copying as a volume
https://github.com/rafaelaazevedo/bug-free-garbanzo/tree/master/galen

**Comment by hypery2k** [comment]
thanks for reporting the issue. I fixed it, you can give the next label from docker hub a try.
