### ISSUE TITLE
integrating Galen with wdio 

### ISSUE THREAD

**Issue by vinilnarayan** [hypery2k/galenframework-cli#66]
> ℹ I am trying to integrate galen with wdio (javascript).
Could you please help me ?

**Comment by hypery2k** [comment]
what does wdio stands for?
There's already a issue regarding nodejs integration see #47

**Comment by vinilnarayan** [comment]
wdio stands for 'Webdriver io".

**Comment by vinilnarayan** [comment]
Hi,
Is there any updates on https://github.com/hypery2k/galenframework-cli/issues/47 ?

Thanks,
Vinil

**Comment by hypery2k** [comment]
ok, no not really. as it's not that easy to integrate.

Will close this issue and track any progress on #47
