### ISSUE TITLE
Remove unused sys dependency

### ISSUE THREAD

**Issue by lo1tuma** [hypery2k/galenframework-cli#8]
If I run `./node_modules/.bin/galen` without arguments I see a deprecation warning in the console:

> sys is deprecated. Use util instead.

That said, it seems like `sys` is not used anywhere, the only occurrence is in one [require statement](https://github.com/hypery2k/galenframework-cli/blob/e1573c09557bf7d24ef323846ee5f3e951c191a9/bin/galen#L3).

**Comment by hypery2k** [comment]
thanks for the hint and suggestions
